[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
royalty_nft = "8mwjmtyM1WQuyhihb1YHV2GERAfTBHJJhTJdZzHMf1UP"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
jest_test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 mocha-tests/**/*.ts"
test = " yarn test"

[test]
startup_wait = 20000
shutdown_wait = 2000
upgradeable = false

[test.validator]
bind_address = "0.0.0.0"
url = "https://api.mainnet-beta.solana.com"
ledger = ".anchor/test-ledger"
rpc_port = 8899
